# Customer Spending Prediciton

In [1]:
#import necessary libraries
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [2]:
#data collection
df = pd.read_csv("ShopSmart_data.csv")
df

,Age,Annual_Income,Website_Visits,Previous_Purchases,Membership_Type,Preferred_Category,City_Tier,Discount_Used,Amount_Spent
0,46,620358.0,11.0,8,Silver,Beauty,Tier 1,Yes,16924.36
1,27,560886.0,13.0,7,Silver,Fashion,Tier 1,No,16467.52
2,52,866655.0,11.0,9,Bronze,Home,Tier 1,No,19224.61
3,55,816016.0,17.0,9,Silver,Home,Tier 2,Yes,20219.63
4,18,355468.0,14.0,0,Bronze,Home,Tier 3,Yes,7345.37
...,...,...,...,...,...,...,...,...,...
1995,47,557297.0,5.0,6,Gold,Home,Tier 1,No,17423.64
1996,46,1027242.0,11.0,12,Bronze,Fashion,Tier 3,No,19939.64
1997,40,677690.0,15.0,4,Bronze,Fashion,Tier 3,Yes,13397.79
1998,34,565410.0,11.0,8,Silver,Electronics,Tier 3,Yes,17682.11
1999,65,397581.0,6.0,8,Bronze,Fashion,Tier 3,No,11165.42

### EDA

In [3]:
#check top few rows
df.head()

,Age,Annual_Income,Website_Visits,Previous_Purchases,Membership_Type,Preferred_Category,City_Tier,Discount_Used,Amount_Spent
0,46,620358.0,11.0,8,Silver,Beauty,Tier 1,Yes,16924.36
1,27,560886.0,13.0,7,Silver,Fashion,Tier 1,No,16467.52
2,52,866655.0,11.0,9,Bronze,Home,Tier 1,No,19224.61
3,55,816016.0,17.0,9,Silver,Home,Tier 2,Yes,20219.63
4,18,355468.0,14.0,0,Bronze,Home,Tier 3,Yes,7345.37

In [4]:
#check bottom few rows
df.tail()

,Age,Annual_Income,Website_Visits,Previous_Purchases,Membership_Type,Preferred_Category,City_Tier,Discount_Used,Amount_Spent
1995,47,557297.0,5.0,6,Gold,Home,Tier 1,No,17423.64
1996,46,1027242.0,11.0,12,Bronze,Fashion,Tier 3,No,19939.64
1997,40,677690.0,15.0,4,Bronze,Fashion,Tier 3,Yes,13397.79
1998,34,565410.0,11.0,8,Silver,Electronics,Tier 3,Yes,17682.11
1999,65,397581.0,6.0,8,Bronze,Fashion,Tier 3,No,11165.42

In [5]:
#check info of dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 2000 non-null   int64
 1   Annual_Income       1984 non-null   float64
 2   Website_Visits      1984 non-null   float64
 3   Previous_Purchases  2000 non-null   int64
 4   Membership_Type     1984 non-null   str
 5   Preferred_Category  1984 non-null   str
 6   City_Tier           2000 non-null   str
 7   Discount_Used       2000 non-null   str
 8   Amount_Spent        2000 non-null   float64
dtypes: float64(3), int64(2), str(4)
memory usage: 182.7 KB

In [6]:
#check missing values
df.isnull().sum()

Age                    0
Annual_Income         16
Website_Visits        16
Previous_Purchases     0
Membership_Type       16
Preferred_Category    16
City_Tier              0
Discount_Used          0
Amount_Spent           0
dtype: int64

In [7]:
#Handle missing values
avg_income = round(df["Annual_Income"].mean())
avg_web_visits= round(df["Website_Visits"].mean())
freq_membership = df["Membership_Type"].mode()[0]
freq_category  = df["Preferred_Category"].mode()[0]

df["Annual_Income"] = df["Annual_Income"].fillna(avg_income)
df["Website_Visits"] = df["Website_Visits"].fillna(avg_web_visits)
df["Membership_Type"] = df["Membership_Type"].fillna(freq_membership)
df["Preferred_Category"] = df["Preferred_Category"].fillna(freq_category)

In [8]:
df.isnull().sum()

Age                   0
Annual_Income         0
Website_Visits        0
Previous_Purchases    0
Membership_Type       0
Preferred_Category    0
City_Tier             0
Discount_Used         0
Amount_Spent          0
dtype: int64

In [9]:
#check duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [Age, Annual_Income, Website_Visits, Previous_Purchases, Membership_Type, Preferred_Category, City_Tier, Discount_Used, Amount_Spent]
Index: []

In [10]:
#check summary of dataset
df.describe()

,Age,Annual_Income,Website_Visits,Previous_Purchases,Amount_Spent
count,2000.000000,2.000000e+03,2000.00000,2000.0000,2000.000000
mean,40.917500,7.525418e+05,9.95650,6.9655,17505.982405
std,12.780116,2.728578e+05,3.09134,2.6235,3866.061235
min,18.000000,1.800000e+05,2.00000,0.0000,6875.410000
25%,32.000000,5.605328e+05,8.00000,5.0000,14864.417500
50%,41.000000,7.520560e+05,10.00000,7.0000,17381.955000
75%,50.000000,9.346820e+05,12.00000,9.0000,19927.317500
max,65.000000,1.604606e+06,20.00000,16.0000,35371.200000

In [11]:
#check numeric data
num_cols = []
for col in df.columns:
    if df[col].dtype!='str':
        num_cols.append(col)
df[num_cols]

      Age  Annual_Income  Website_Visits  Previous_Purchases  Amount_Spent
0      46       620358.0            11.0                   8      16924.36
1      27       560886.0            13.0                   7      16467.52
2      52       866655.0            11.0                   9      19224.61
3      55       816016.0            17.0                   9      20219.63
4      18       355468.0            14.0                   0       7345.37
...   ...            ...             ...                 ...           ...
1995   47       557297.0             5.0                   6      17423.64
1996   46      1027242.0            11.0                  12      19939.64
1997   40       677690.0            15.0                   4      13397.79
1998   34       565410.0            11.0                   8      17682.11
1999   65       397581.0             6.0                   8      11165.42

[2000 rows x 5 columns]

Scaling should be done on these numeric columns

In [12]:
#check object  data
for col in df.columns:
    if df[col].dtype=='str':
        print(col,"      :",list(df[col].unique()))

Membership_Type       : ['Silver', 'Bronze', 'Gold']
Preferred_Category       : ['Beauty', 'Fashion', 'Home', 'Electronics']
City_Tier       : ['Tier 1', 'Tier 2', 'Tier 3']
Discount_Used       : ['Yes', 'No']

Encoding needs to be done on these object columns

### Model Pipeline

In [13]:
#Divide the data into input and output features
X = df.drop("Amount_Spent",axis=1)
y = df.Amount_Spent

In [14]:
#Split training and testing dataset
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3,random_state=42)

In [15]:
#Separate numeric and object columns
num_cols = Xtrain.select_dtypes(include="number").columns
cat_cols = Xtrain.select_dtypes(include="str").columns

In [16]:
#multi model pipelines
models = {"Linear Regression": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",LinearRegression())]),
          "Ridge": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",Ridge(alpha=50))]),
          "Lasso": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",Lasso(alpha=100))]),
          "KNN": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",KNeighborsRegressor(n_neighbors=6))]),
          "Decision Tree": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",DecisionTreeRegressor(max_depth=10))]),
          "Random Forest": Pipeline([("preprocessor",ColumnTransformer([("encoder",OneHotEncoder(),cat_cols),
                                                                            ("scaler",StandardScaler(),num_cols)])),
                                         ("model",RandomForestRegressor(n_estimators=100,max_depth=6,random_state=42))]),

}

In [17]:
#multi - model training
model_perf = {}
for model_name,pipeline in models.items():
    pipeline.fit(Xtrain,ytrain)
    ypred = pipeline.predict(Xtest)
    r2 = r2_score(ytest,ypred)
    mse = mean_squared_error(ytest,ypred)
    mae = mean_absolute_error(ytest,ypred)
    model_perf[model_name] = {"R2":r2,"MSE":mse,"MAE":mae}

In [18]:
#model performance table
perf_df = pd.DataFrame(model_perf)
perf_df

,Linear Regression,Ridge,Lasso,KNN,Decision Tree,Random Forest
R2,0.948411,0.945508,9.219361e-01,8.305840e-01,7.717924e-01,8.286898e-01
MSE,748773.147905,790913.976980,1.133044e+06,2.458957e+06,3.312277e+06,2.486451e+06
MAE,617.571794,637.820955,8.214268e+02,1.221249e+03,1.401779e+03,1.241418e+03

In [19]:
#fetch best model
best_model = max(model_perf.items(),key = lambda t:t[1]["R2"] )
print(best_model)
best_model_name = best_model[0]
best_pipeline = models[best_model_name]

('Linear Regression', {'R2': 0.9484114030748212, 'MSE': 748773.1479047127, 'MAE': 617.5717936465328})

In [20]:
#predictions
best_pipeline.predict(Xtest)

array([14300.70821746, 18868.39803924, 21971.15353009, 18737.94405993,
       16436.42119351, 17202.76154403, 15377.20150439, 21325.65246883,
       15865.06206069, 17277.42577381, 13888.14976577, 16093.40582274,
       13677.31782594, 17415.88257148, 15663.74260122, 10125.80259628,
       18838.29969687, 22163.78213348, 15654.46952326, 15196.37727142,
       19751.23780891, 18291.28036664, 17704.59403663, 17981.41677218,
       15263.22950359, 20738.0649449 , 17682.11238067, 17959.57952301,
       18354.74055789, 12602.2609369 , 15750.38863006, 13783.45246416,
       28358.7905974 , 17406.7892587 , 16593.83373872, 15833.40324013,
       16347.84898046, 18796.29947389, 14010.96415369, 20601.09709545,
       16641.1926763 ,  9845.65563136, 16165.36509138, 23541.32722822,
       19370.07059054, 20790.03422243, 16708.21877095, 17124.57748792,
       19334.39449236, 23177.65065194, 18636.64185262, 12833.74443307,
        7984.53431687, 24789.60762942, 20556.17864924, 13783.75242183,
       16997.49275327, 13515.06775693, 12930.17430085, 19600.07057269,
       20483.08054408, 11906.16403038, 13468.61500471, 18805.05640151,
       15265.65853311, 23762.41396229, 23357.43340567, 18387.38478775,
       20824.49996444, 21067.19202443, 17993.15203745, 13969.17489248,
       23053.51381071, 20922.62054043, 14918.45565845, 11780.60098484,
       19536.6059561 , 15369.56545167, 11275.11707407, 21866.55219117,
       15342.13695571, 22011.65909593, 18315.92215535, 17612.68603742,
       14572.30136622, 17638.60532055, 21436.47284651, 17694.54594825,
       20513.77578624, 15960.11683667, 18501.05095811, 14511.63779081,
       20550.17986561, 12768.37130352, 14323.26125832, 18763.21180566,
       11857.59109899, 20056.3549546 , 19348.1307153 , 16475.20879517,
       21868.39034766, 25050.37753464, 20903.67902496, 18259.78374957,
       15445.61609462, 18729.73636705, 12417.50170542, 13889.83887881,
       15777.80019579, 18807.10833291, 23226.16565951, 15897.42414356,
       19844.93852065, 14931.12292936, 20717.04160748, 11891.80325538,
       22241.56798478, 12892.62868316, 21805.33727735, 20980.16780231,
       14777.74969119, 18714.48297813, 14518.2247849 , 22466.70516063,
       18333.15152345, 22513.01783605, 15630.8992069 , 18684.98102472,
       11471.87771762, 23605.51004005, 11466.62742984, 10538.72216028,
       22971.27761093, 13865.3008642 , 21176.49993561, 12521.89635379,
       20454.05403531, 28222.40960989, 15456.99334329, 15341.95622034,
       17799.64344018, 21502.90224657, 16430.42210236, 19907.74419221,
       18519.38561342, 23336.11960582, 21579.41313123, 15902.37013742,
       28057.35113032, 19828.11952591, 16565.16306337, 19054.54356669,
       22734.73230427, 21032.66126036, 16912.65378449, 16067.96121745,
       19207.96673642,  9573.70176514, 22043.59027834,  8621.44721094,
       17298.73443789, 17307.75910833, 15902.17611696, 13403.17768   ,
       13076.87847268, 17816.51270588, 17835.86811629, 20107.66574126,
       18953.60270725, 15762.47109143, 23044.02664969, 18045.16589768,
       13171.34580672, 15359.05769818, 20435.20538432, 21845.36559862,
       20145.51296075, 16872.15328985, 14454.03912011, 20730.66635505,
       13634.320188  , 17789.69327293, 19462.54678911, 20361.11343485,
        8067.94355472, 18772.02655531, 17945.50406676, 17390.01450964,
       13707.9095672 , 15190.99566407, 20927.7190392 , 17084.06856632,
       19248.0812369 , 14754.87300122, 16725.95442578, 15286.05282975,
       18661.29972653, 21824.96293682, 17361.40850953, 13859.64022255,
       16738.67331318, 19221.09570978, 11731.42706587, 15215.18212001,
       16447.30778785, 19056.88670079, 20631.45560032, 19552.62332533,
       18156.10135725, 15036.60714166, 20962.18008431, 21210.90765074,
       11347.00672577, 22565.04449725, 15109.98657607, 20142.02997847,
       19486.86433521, 17376.61179809, 18762.12000285, 19173.53613848,
       18612.70350502, 15547.32882736, 22471.80137901, 14007.72384205,
       16290.1335485 , 17055.02958092, 18039.37807412, 15853.90863535,
       19277.78413075, 17520.97168174, 20837.27760453, 21254.39667669,
       19176.97535291, 21171.33892476, 18387.07875784, 16612.7272212 ,
       12347.31746288, 14485.4137134 , 16975.20543246, 17744.79517054,
       12827.90933136, 15582.12630787, 16151.7342605 , 19672.08078885,
       15288.38609217, 19004.92361211, 22152.43168793, 19201.49870533,
       16788.20881686, 15935.28783599, 15932.99262241, 16573.58671153,
       14368.05557254, 15897.55368299, 16184.82426275, 12338.30017846,
       21611.57881704, 20809.26990836, 21125.15566378, 24173.61036827,
       17231.35205766, 21622.6086447 , 19038.50139826, 16556.97384187,
       19240.52630389, 13682.96472863, 17237.1705135 , 19288.87049527,
       21852.02608188, 19564.95237954, 19620.31337125, 14440.38276633,
       21797.79790775, 19265.70868337, 12430.04165112, 21911.38618662,
       10894.67719356, 17587.60360866, 15733.60905803, 16317.24560939,
       10316.67822579, 23094.31985349, 20399.74459123, 16439.49618756,
       20545.23122826, 18140.08320277, 19973.08469266, 17540.22439602,
       19769.86767422, 22249.91259619,  9177.73423525, 17292.87200032,
       21610.82741382, 17433.88936779, 27273.18903936, 18734.90621813,
       12221.05087778, 12637.48720403, 28765.27526256, 11480.19010613,
       19836.95356672, 17674.38554026, 15336.99227006, 12168.30647522,
       22543.22663006, 19221.71117292, 16325.30714364, 18424.27071165,
       19713.54469031, 22065.7879476 , 14578.04863648, 17883.19396281,
       13845.20679158, 19354.65517958, 21567.7767824 , 15640.97647163,
       13338.83357204, 14533.90779039, 16118.39586532, 18363.94575917,
       12642.04815412, 12971.64594215, 14320.66477135, 15327.65651914,
       22948.81339698, 17003.58058821, 17562.92855639, 16886.39467262,
       15969.23033406, 17929.94342922, 21418.51239994, 19198.99035212,
       19979.1234315 , 18080.98707457, 15796.24689938, 18674.12115608,
       16433.84755936, 16148.80384505, 17648.6150848 , 19347.887886  ,
       14865.97569766, 17492.77271773, 12417.90287285, 21565.53863074,
       21892.33111791, 22170.47827004, 18615.12218809, 21342.12027536,
       19062.36386351, 15906.3691744 , 15392.59949954, 18562.97418665,
       17289.59056639, 23888.36463671, 15747.42273818, 22310.46431803,
       12937.80686668, 18341.10766972, 12294.08012721, 15114.4385042 ,
       15449.37647281, 14713.94530257, 16367.61020825, 15850.49875541,
       17577.55962601, 16681.98442941, 16921.43883154, 19963.78129436,
       15100.12822329, 21255.24932951, 15460.17730683, 15290.80162391,
       19834.16979919, 20913.41692583, 23238.78878844, 14808.92298321,
       24489.24574171, 20258.95005825, 19959.42307512, 22877.02522801,
       23026.11676301, 15329.65534547, 18214.96882266, 14771.25919686,
       21139.63783071, 13492.60647237, 13253.79422348, 20886.13502555,
       17758.41563814, 19866.09931968, 16677.74462446, 12337.95475435,
       17619.54843887, 14587.59002612, 11304.20291947, 11380.65005596,
       11354.56235964, 17246.05969769, 20336.66813908, 22095.87514743,
       26573.83601551, 21779.78706153, 15959.60497024, 16919.04036313,
       10977.3609466 , 23255.64128262, 16918.00537494, 22558.46295109,
       21763.73599263, 24271.47966866, 15188.11948793, 15643.22582087,
       20304.59812805, 18545.46224929, 15365.20125596, 21661.79435621,
       16821.04314199, 12076.51837382, 17951.07806416, 21340.88786972,
       14780.30972879, 19788.8475888 , 16854.5135872 , 16873.1645185 ,
       10893.45038745, 18617.29451152, 18716.7936406 , 22966.70457437,
       12059.98502103, 20240.69161259, 26366.27639389, 19830.66118449,
       21279.35393679, 13521.48661167, 16684.22832875, 17651.41367032,
       15894.57616894, 14715.54965651, 15812.23740444, 15006.87676032,
       13754.04628626, 13176.42096363, 17373.91857567, 21123.45139146,
       13147.58572643, 21518.68955196, 13407.29106192, 16681.66559576,
       20233.08538397, 16581.16436442, 21106.08832907, 18076.12261288,
       19502.74189606, 14959.44672689, 21034.57039842, 12188.97843144,
       21156.95695417, 17061.42832458, 24388.94799888, 20202.6976778 ,
       19367.60100548, 18061.38972138, 21980.36421333, 14273.62089414,
       18310.24176341, 11859.79866559, 12840.86167814, 15400.6245189 ,
       21947.09164423, 20947.48114439, 25024.02768032, 23011.71634284,
       21834.26927234, 14630.53649357, 16866.775275  , 18655.67229694,
       23118.63702067, 17130.63242109, 27820.72044135, 20466.16836834,
       12418.11182313, 20952.93529434, 12266.01183158, 11777.06995069,
       20214.70760295, 18461.23964306, 14465.50623421, 21056.24940058,
       22207.9072893 , 18479.13661656, 23409.92169879, 26066.11808127,
       10200.580778  , 18418.29814535, 10321.7276013 , 12376.28492574,
       10962.08042395, 13357.77389594,  7956.17794537, 18190.30844835,
       13487.62672781,  8814.49396527,  9407.10123337, 15112.04181874,
       21255.64052019, 20562.30117074, 20151.34054149, 10309.81987921,
       16592.09840561, 14384.90687668, 18076.04677022, 19589.88146232,
       13017.70215428, 23119.43416407, 15468.68417777, 17487.49867574,
       20378.77827896, 20228.01645959, 20550.32073794, 18302.48180285,
       21292.67503733, 22653.14423908, 21980.2592168 , 24736.87116032,
       11245.16451384, 16044.13867308, 19248.52984502, 14567.21609188,
       12233.61230002, 17140.53726679, 16135.29691823, 17456.60311541,
       13403.74577491, 11408.74131547, 13282.62373227, 18797.76495993,
       18356.46823754, 16373.77108071, 11133.65310414, 17211.19007166,
       15208.40118105, 20598.00555338, 14768.12906808, 14560.48919338,
       15492.39587694, 19152.009416  , 15732.27886119, 12438.49389855,
       10117.13922677, 21314.17608755, 15249.05317441, 14154.32097691,
       18002.78696056, 24195.0191836 , 11252.33427833, 19170.90294977,
       20865.39398349, 16238.46744386, 16023.43778698, 14612.17508644,
        9091.84067559, 18553.76314545, 22462.29336627, 18991.9152432 ,
       24716.74704271, 16094.01954376, 19716.24215386, 11421.53599716,
       15043.56932351, 11643.50888671, 19309.52053622, 19686.21858019,
       16475.15125354, 17906.82050224, 17424.74468439, 26475.00613005,
       24191.77550121, 21797.32875408, 18056.94708355, 10853.39252723,
       11178.61300595, 19514.84583271, 18930.73352705, 20861.19074818,
       14620.83205285, 14027.11945736, 18670.451368  , 13858.87039969,
       16892.70579551, 22163.59518631, 17160.28443154, 16400.33284972,
       16368.86138351, 13178.43004009, 17590.08077617, 10486.95048157,
       18702.55945509, 16489.67387779, 19498.58847314, 16987.26076566])

In [21]:
#save best model pipeline
import pickle
with open("best_model_pipeline.pkl","wb") as file:
    pickle.dump(best_pipeline,file)

In [22]:
#save cleaned df
df.to_csv("cleaned_data.csv")

In [23]:
Xtrain.columns

Index(['Age', 'Annual_Income', 'Website_Visits', 'Previous_Purchases',
       'Membership_Type', 'Preferred_Category', 'City_Tier', 'Discount_Used'],
      dtype='str')